#!/bin/bash
## resource allocation

#SBATCH --chdir=/home/veeliad/work

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64g
#SBATCH --gres=gpu:a100:1
#SBATCH --qos=gpu

#SBATCH --job-name={model_name}-{timestamp}
#SBATCH --output=%x-%j.out  # %x => job-name, %j => jobid
#SBATCH --error=%x-%j.err


## run time
singularity run --fakeroot --overlay TEST/overlay --nv --env device=cuda --env fold_index={fold_index} --env task_number={task_number} --pwd /stroke_segmentation --mount type=bind,source=/home/veeliad/work/output,destination=/stroke_segmentation/nnunet_results training_big_lesions.sif


