#!/bin/bash
## resource allocation

#SBATCH --chdir=/home/veeliad/work/BrainSegmentation/images

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64g
#SBATCH --gres=gpu:a100:1
#SBATCH --qos=gpu

#SBATCH --job-name={model_name}-{timestamp}-training
#SBATCH --output=%x-%j.out  # %x => job-name, %j => jobid
#SBATCH --error=%x-%j.err


## run time
singularity run --fakeroot --writable-tmpfs --nv \
  --env device=cuda \
  --env configuration={configuration} \
  --env task_number={task_number} \
  --pwd /stroke_segmentation \
  --bind {model_path}:/stroke_segmentation/nnunet_results \
  training_latest.sif